//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilgamPortalRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipalities
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string EngName { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool Active { get; set; }
        public string ContactFullName { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPhone { get; set; }
        public string GeneralRemarks { get; set; }
        public string HeaderLogo { get; set; }
        public string SmallLogo { get; set; }
    }
}
